# Generated by Django 4.2.6 on 2023-11-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
