# Generated by Django 4.2.7 on 2023-11-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
