# Generated by Django 4.2.6 on 2023-10-30 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalendar.task'),
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='notification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalendar.notifications'),
        ),
    ]
