# Generated by Django 4.2.7 on 2023-11-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
