# Generated by Django 4.2.6 on 2023-10-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendar', '0002_remove_schedule_schedule_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('task_source', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('notes', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalendar.location')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalendar.schedule')),
            ],
        ),
    ]
