# Generated by Django 4.2.6 on 2023-10-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalendar', '0003_location_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('notification_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('Email', 'Email'), ('Push', 'Push'), ('Text', 'Text')], default='Email', max_length=5)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalendar.Event')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalendar.notifications')),
            ],
        ),
    ]
