# Generated by Django 4.2.7 on 2023-11-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        
    ]
