# Generated by Django 4.2.7 on 2023-11-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name = 'CustomUser',
            old_name ='user_id',
            new_name = 'id',
        ),
    ]
