# Generated by Django 4.2.7 on 2023-11-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0003_remove_customuser_phone_number_alter_customuser_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
