# Generated by Django 4.2.6 on 2023-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
